### ISSUE TITLE
its doesn't upload

### ISSUE THREAD

**Issue by dostundegil** [sujay1599/InstagramTheftyScraperPosterHuman#6]
it just doesn't upload and i don't know why

![image](https://github.com/user-attachments/assets/f32d8edb-dfd6-4d73-befb-050286d73cd4)

**Comment by dostundegil** [comment]
I think it bugs out when the user's username contains an underscore ('_') during scraping.  It's scraping but when it upload one time it's done.

**Comment by sujay1599** [comment]
Your session needs to be updated. 
Try reloging in

**Comment by sujay1599** [comment]
I am working on away to save the session  
Consider starting for setup.py and then running main.py 

Always use same uuid for same account. 

Lmk if that helps. 

CJ

**Comment by iekamjotsingh** [comment]
@sujay1599 Description isn't getting uploaded when using custom description

**Comment by sujay1599** [comment]
May you post config file!?

**Comment by iekamjotsingh** [comment]
> May you post config file!?

credit:
  give_credit: false
custom_tags:
- baby
- cute
- fyp
- explore
deleting:
  delete_interval_minutes: 5
description:
  custom_description: ' '
  use_original: false
hashtags:
  use_hashtags: false
instagram:
  password: 
  username: 
key: 
leave_comment: false
scraping:
  enabled: true
  like_reels: true
  num_reels: 4
  profiles: cute_baby_reels_12 cute_baby_status7 cutenatiboy cute__babies__reel
  scrape_interval_minutes: 4
uploading:
  add_to_story: true
  enabled: true
  upload_interval_minutes: 60

**Comment by sujay1599** [comment]
so are you trying to upload your own descriptions? 
if so you must setup like so.
![image](https://github.com/user-attachments/assets/c7d8add3-64e0-42d0-b3e7-887659adef66)

in setup_config.py:
Use original description? (true/false): false
Enter custom description (leave blank to use default descriptions): Follow me for memes. Daily new content! 
Add hashtags? (true/false): false
Give credit? (true/false): false

If you leave blank default default descriptions are located in upload.py line 14. 
You can add additional default descriptions to the list and it will randomly add. 

description is built like this:
![image](https://github.com/user-attachments/assets/b467278e-5ac1-4b88-ac56-8039c695f30e)


Use original description? (true/false): true means it will use the original description taken from scraped video 
Use original description? (true/false): false will prompt for custom description you want to add (see my image above)
if you leave this portion blank it will use random DEFAULT_DESCRIPTIONS from upload.py

Add hashtags? (true/false): ture will prompt you to also enter #tags which are just appended to the end of the description; theoretically you can put anything here; sometimes I put Follow me @acc @acc2 @acc3 

lastly Give credit? (true/false): true will just append where username whom the video was scraped from "\nTaken from: @{profile_username}"


Does this make sense or help? 

Let me know because it works for me! 

Thanks,
CJ



Default descriptions

**Comment by iekamjotsingh** [comment]
Yes, I'm using the default description. Just replacing the instagram handle and its going blank while uploading, nothing is uploaded with the reel.

**Comment by sujay1599** [comment]
I like to scrape a lot of videos from 5 accounts or so and set interval to 360 + then upload at every 45-60; works well for me! 

CJ

**Comment by iekamjotsingh** [comment]
Are you available through google meet or some ?

**Comment by sujay1599** [comment]
not at the moment.

Delete the session.json file
run setup_config.py
then run main.py


when you log into another user, you must move ur current session.json to another location or else your account will be flagged and will require password change. 

your original email was showing login required so your session.json needs to be deleted and you need to relogin .

try from start.

I am running it right now! 

can meet later

**Comment by iekamjotsingh** [comment]
Testing again, will let you know. Please drop your discord or tg if possible.

**Comment by sujay1599** [comment]
Add me as a friend on Discord! Invite expires in 1 week: https://discord.gg/b5FgpBf2

**Comment by iekamjotsingh** [comment]
sent

**Comment by sujay1599** [comment]
should be working!
